# Generated by Django 5.0.6 on 2024-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_catagory_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
